# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0072-08E9";
      fsType = "vfat";
    };

  fileSystems."/var/lib/private/nimbus-beacon-node" =
    { device = "rpool/nimbus";
      fsType = "zfs";
    };

  fileSystems."/mnt/erigon" =
    { device = "rpool/erigon";
      fsType = "zfs";
    };

  fileSystems."/var/lib/private/nimbus-beacon-node/secrets" =
    { device = "rpool/secret/nimbus/secrets";
      fsType = "zfs";
      options = [ "noauto" "nofail" ];
    };

  fileSystems."/var/lib/private/nimbus-beacon-node/validators" =
    { device = "rpool/secret/nimbus/validators";
      fsType = "zfs";
      options = [ "noauto" "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/18bcf304-1edf-4ffc-99e1-e0fb501e42ab"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enP4p1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.ztbto5ttab.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
