#!/usr/bin/env bash

HOST=$(hostname)
if [[ ! -z "$1" ]]; then
    HOST="$1"
fi

if [[ ! -e "secrets.nix" ]]; then
    echo "Missing 'secrets.nix' file!" >&2; exit 1;
fi
if [[ ! -e "hosts/${HOST}/configuration.nix" ]]; then
    echo "Missing 'hosts/${HOST}/configuration.nix' file!" >&2; exit 1;
fi
if [[ ! -e "hosts/${HOST}/hardware-configuration.nix" ]]; then
    echo "Missing 'hosts/${HOST}/hardware-configuration.nix' file!" >&2;
fi

# symlink host config
ln -vsf "${PWD}/hosts/${HOST}/configuration.nix" "${PWD}"
ln -vsf "${PWD}/hosts/${HOST}/hardware-configuration.nix" "${PWD}"

# and then the whole dir
if [[ -h "/etc/nixos" ]]; then
    echo "The /etc/nixos path is already a symlink!" >&2
    ls -l "/etc/nixos"
elif [[ "${PWD}" != "/etc/nixos" ]]; then
    sudo rm -rf "/etc/nixos"
    sudo ln -vsf "${PWD}" "/etc/nixos"
fi
