#!/usr/bin/env bash

HOST=$(hostname)
if [[ ! -z "$1" ]]; then
    HOST=$1
fi

FILES=(
  "secrets.nix"
  "hosts/$HOST/configuration.nix" 
  "hosts/$HOST/hardware-configuration.nix" 
)

for FILE in ${FILES[@]}; do
    if [[ ! -e "${FILE}" ]]; then
        echo "Missing '${FILE}' file!" >&2
        exit 1
    fi
done

rm -r "/etc/nixos"
ln -vsf "$PWD/hosts/$HOST" "/etc/nixos"
