---
groups:
  - name: instance
    rules:
    # Alert for any instance that is unreachable for >5 minutes.
    - alert: InstanceDown
      expr: up == 0
      for: 5m
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
        current_value: "{{ $value }}"

    # Alert for any instance that has too low disk space
    - alert: LowRootDiskSpace
      expr: netdata_disk_space_GiB_average{family="/", dimension="avail", fleet!~".*test.*"} < 1
      for: 1m
      annotations:
        summary: "Low root disk space on {{ $labels.instance }}" 
        description: "{{ $labels.instance }} has less root disk space left than 1 GB." 
        current_value: "{{ $value }}" 

    # Alert for any instance that has too high CPU usage
    - alert: HighCPUUsage
      expr: netdata_cpu_cpu_percentage_average{dimension="user", fleet!~".*test.*"} >= 98
      for: 30m
      annotations:
        summary: "Low disk space on {{ $labels.instance }}" 
        description: "{{ $labels.instance }} has CPU usage higher than 98% for over 30 minutes." 
        current_value: "{{ $value }}" 
