# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2178-694E";
      fsType = "vfat";
    };

  fileSystems."/mnt/music" =
    { device = "USB-HDD/music";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/mnt/git" =
    { device = "USB-HDD/git";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/mnt/mobile" =
    { device = "USB-HDD/mobile";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/mnt/photos" =
    { device = "USB-HDD/photos";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/mnt/data" =
    { device = "USB-HDD/data";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/mnt/torrent" =
    { device = "USB-HDD/torrent";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
