# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f770ee52-b56b-43d8-9f5f-003d3d7ef24d";
      fsType = "ext4";
    };

  fileSystems."/mnt/data" =
    { device = "DATA/data";
      fsType = "zfs";
    };

  fileSystems."/mnt/git" =
    { device = "DATA/git";
      fsType = "zfs";
    };

  fileSystems."/mnt/music" =
    { device = "DATA/music";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 2;
}
