# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/mnt/data" =
    { device = "rpool/DATA/data";
      fsType = "zfs";
    };

  fileSystems."/mnt/git" =
    { device = "rpool/DATA/git";
      fsType = "zfs";
    };

  fileSystems."/mnt/music" =
    { device = "rpool/DATA/music";
      fsType = "zfs";
    };

  fileSystems."/mnt/mobile" =
    { device = "rpool/DATA/mobile";
      fsType = "zfs";
    };

  fileSystems."/mnt/photos" =
    { device = "rpool/DATA/photos";
      fsType = "zfs";
    };

  swapDevices = [ ];

}

