# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot1" =
    { device = "/dev/disk/by-uuid/81617663-3358-45a2-8bc6-464de916d44b";
      fsType = "ext4";
    };

  fileSystems."/boot2" =
    { device = "/dev/disk/by-uuid/840f87e0-ccb3-4817-a0d1-08735ebddefb";
      fsType = "ext4";
    };

  fileSystems."/var/lib/private/goethereum" =
    { device = "DATA/geth";
      fsType = "zfs";
      options = [ "nofail" ];
     };

  fileSystems."/mnt/nimbus" =
    { device = "rpool/nimbus";
      fsType = "zfs";
    };

  fileSystems."/mnt/nimbus/secrets" =
    { device = "rpool/secret/nimbus/secrets";
      fsType = "zfs";
      options = [ "noauto" "nofail" ];
    };

  fileSystems."/mnt/nimbus/validators" =
    { device = "rpool/secret/nimbus/validators";
      fsType = "zfs";
      options = [ "noauto" "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2d4d3916-cb52-4b87-8c73-819c98026868"; }
      { device = "/dev/disk/by-uuid/620f2e0f-8d4e-4378-8583-cca502d226ef"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
