# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "mpt3sas" "xhci_pci" "firewire_ohci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "SYSTEM";
      fsType = "zfs";
    };

  fileSystems."/mnt/git" =
    { device = "DATA/git";
      fsType = "zfs";
    };

  fileSystems."/mnt/music" =
    { device = "DATA/music";
      fsType = "zfs";
    };

  fileSystems."/mnt/torrent" =
    { device = "MEDIA/torrent";
      fsType = "zfs";
    };

  fileSystems."/mnt/data" =
    { device = "DATA/data";
      fsType = "zfs";
    };

  fileSystems."/mnt/ania" =
    { device = "DATA/ania";
      fsType = "zfs";
    };

  fileSystems."/mnt/backup" =
    { device = "DATA/backup";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/58af9ff6-9fe1-45ef-803c-f5699b1becf9"; }
      { device = "/dev/disk/by-uuid/53f42441-293f-42f8-9eb4-aeb0213acee0"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  # High-DPI console
  console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
